# Generated by Django 2.0.7 on 2018-07-14 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255, verbose_name='Имя')),
                ('lname', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('pname', models.CharField(max_length=255, verbose_name='Отчество')),
                ('year', models.IntegerField(verbose_name='Год рождения')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.IntegerField(verbose_name='ISBN')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('year', models.IntegerField(verbose_name='Год издания')),
            ],
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(choices=[(0, 'Нет'), (1, 'Бакалавр'), (2, 'Магистр'), (3, 'Кандидат технических наук'), (4, 'Доктор технических наук')], verbose_name='Научная степень')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Факультет')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=django.db.models.deletion.DO_NOTHING, verbose_name='Прикрепленный файл')),
                ('isbn', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.Book')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255, verbose_name='Имя')),
                ('lname', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('pname', models.CharField(max_length=255, verbose_name='Отчество')),
                ('year', models.IntegerField(verbose_name='Год поступления')),
                ('gender', models.IntegerField(choices=[('М', 'Мужской'), ('Ж', 'Женский')], verbose_name='Пол')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.Faculty')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Пользователь', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
