# Generated by Django 2.0.7 on 2018-07-14 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20180714_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.Author'),
        ),
        migrations.AlterField(
            model_name='author',
            name='year',
            field=models.IntegerField(default=2003, verbose_name='Год рождения'),
        ),
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.IntegerField(default=2018, verbose_name='Год издания'),
        ),
    ]
