# Generated by Django 2.0.7 on 2018-07-14 12:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20180714_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='isbn',
        ),
        migrations.AddField(
            model_name='file',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Книга', to='catalog.Book'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999999)], verbose_name='ISBN'),
        ),
    ]
