# Generated by Django 2.0.7 on 2018-07-14 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20180714_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='uploads/%Y/%m/%d/', verbose_name='Прикрепленный файл'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.IntegerField(choices=[('0', 'Мужской'), ('1', 'Женский')], verbose_name='Пол'),
        ),
    ]
