# Generated by Django 2.0.7 on 2018-07-14 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20180714_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Мужской'), (1, 'Женский')], verbose_name='Пол'),
        ),
    ]
