# Generated by Django 2.0.7 on 2018-07-14 14:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20180714_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Copy',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('a11b594c-a674-4c97-848f-d169734db637'), primary_key=True, serialize=False)),
                ('loanStart', models.DateField(null=True, verbose_name='Дата сдачи')),
                ('loanDuration', models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(30)], verbose_name='Срок сдачи')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.Book', verbose_name='Книга')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.Student', verbose_name='Студент')),
            ],
        ),
    ]
