# Generated by Django 2.0.7 on 2018-07-14 14:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_copy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copy',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7ac55010-c404-4cff-8ca7-da3b612231c8'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='copy',
            name='loanDuration',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(30)], verbose_name='Срок сдачи'),
        ),
        migrations.AlterField(
            model_name='copy',
            name='loanStart',
            field=models.DateField(blank=True, null=True, verbose_name='Дата сдачи'),
        ),
        migrations.AlterField(
            model_name='copy',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.Student', verbose_name='Студент'),
        ),
    ]
