# Generated by Django 2.0.7 on 2018-07-14 14:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20180714_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copy',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('4513ddcc-11a7-4478-8123-a8ee7a77c55e'), editable=False, primary_key=True, serialize=False),
        ),
    ]
