# Generated by Django 2.0.7 on 2018-07-15 07:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20180714_2140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='copy',
            options={'ordering': ['-book']},
        ),
        migrations.AlterField(
            model_name='copy',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
